### PR TITLE
Check for username on GitHub before sending invitation. Fixes #8

### LINKED ISSUE #8: User validation done properly
Use octokit to verify if the user exists and then proceed for the invitation

### PR DESCRIPTION
**Pull request by Ryuno-Ki**

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
During the work on this project I had some remarks. Are you open for filling issues on them?

**Comment by ionicc** [comment]
Absolutely @Ryuno-Ki 😄

**Review by ionicc — COMMENTED** [review]
@Ryuno-Ki Have you checked this feature addition properly? I had the same implementation but 
`client.users.getByUsername()` would return me errors or pending promises.

**Comment by Ryuno-Ki** [comment]
I ran the program on my local machine (and spotted a security issue with GitHub).
Personally, I'd say, the issue is not precise enough.

I'd expect the user to be informed somehow, that the username could not be found. The HTTP status code should be [400](https://http.cat/400) then. The same behaviour should happen on empty username.

Right now, the implementation does not allow that.

I checked what happens if I enter an username like `goawaynow`. I execute the `catch` callback.
If I enter an username like `nobody`, the then callback is executed.

In my opinion, this is what the issue is asking for.
I'd fill follow-up tickets with general improvements.

**Comment by Ryuno-Ki** [comment]
I filled follow-up issues and linked them to #8

**Review by ionicc — APPROVED** [review]
Alright great! Thanks for your contribution 😄 
Looking forward to more of your work.

**Pull request merged**
